package release

import (
	"fmt"
	"os"
	"os/exec"
	"regexp"
	"strconv"
	"strings"
)

var (
	explicitBumpRE = regexp.MustCompile(`(?im)^(?:semver[- ]bump|release[- ]bump):\s*(major|minor|patch)\b`)
	breakingRE     = regexp.MustCompile(`(?im)^(BREAKING CHANGE:|[a-z][a-z0-9_-]*(?:\([^)]*\))?!:)`)
	minorRE        = regexp.MustCompile(`(?im)^(feat(?:\([^)]*\))?:|add(?:ed|s)?\b|creat(?:e|ed|es)\b|implement(?:ed|s)?\b|introduc(?:e|ed|es)\b|support(?:ed|s)?\b)`)
	patchRE        = regexp.MustCompile(`(?im)^(fix|docs?|chore|test|tests|refactor|update|remove|repair)\b`)
	semverRE       = regexp.MustCompile(`^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$`)
	goVersionRE    = regexp.MustCompile(`(?m)^var Version = "([^"]+)"$`)
)

const EmptyTree = "4b825dc642cb6eb9a060e54bf8d69288fbee4904"

func InferBump(messages string, changedFiles []string) string {
	if match := explicitBumpRE.FindStringSubmatch(messages); len(match) > 1 {
		return strings.ToLower(match[1])
	}
	if breakingRE.MatchString(messages) {
		return "major"
	}
	if minorRE.MatchString(messages) {
		return "minor"
	}
	if patchRE.MatchString(messages) {
		return "patch"
	}
	for _, file := range changedFiles {
		if strings.HasPrefix(file, ".github/workflows/") {
			return "minor"
		}
	}
	return "patch"
}

func BumpVersion(version string, bump string) (string, error) {
	match := semverRE.FindStringSubmatch(version)
	if len(match) != 4 {
		return "", fmt.Errorf("unsupported version %q; expected MAJOR.MINOR.PATCH", version)
	}
	major, _ := strconv.Atoi(match[1])
	minor, _ := strconv.Atoi(match[2])
	patch, _ := strconv.Atoi(match[3])
	switch bump {
	case "major":
		return fmt.Sprintf("%d.0.0", major+1), nil
	case "minor":
		return fmt.Sprintf("%d.%d.0", major, minor+1), nil
	case "patch":
		return fmt.Sprintf("%d.%d.%d", major, minor, patch+1), nil
	default:
		return "", fmt.Errorf("unsupported bump %q", bump)
	}
}

func ReadVersion(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(data)), nil
}

func WriteVersion(path string, version string) error {
	return os.WriteFile(path, []byte(version+"\n"), 0o644)
}

func WriteGoVersion(path string, version string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	updated := goVersionRE.ReplaceAllString(string(data), `var Version = "`+version+`"`)
	if updated == string(data) {
		return fmt.Errorf("could not update Go version in %s", path)
	}
	return os.WriteFile(path, []byte(updated), 0o644)
}

func ChangedFiles(base string, head string) ([]string, error) {
	out, err := git("diff", "--name-only", "--diff-filter=ACMRT", base, head)
	if err != nil {
		return nil, err
	}
	var files []string
	for _, line := range strings.Split(out, "\n") {
		if strings.TrimSpace(line) != "" {
			files = append(files, strings.TrimSpace(line))
		}
	}
	return files, nil
}

func CommitMessages(base string, head string) (string, error) {
	if base == EmptyTree {
		return git("log", "--format=%B%n---END-COMMIT---", head)
	}
	return git("log", "--format=%B%n---END-COMMIT---", base+".."+head)
}

func UsableBase(base string, head string) string {
	if base == "" || strings.Trim(base, "0") == "" {
		return FallbackBase(head)
	}
	if _, err := git("cat-file", "-e", base+"^{commit}"); err != nil {
		return FallbackBase(head)
	}
	return base
}

func FallbackBase(head string) string {
	if out, err := git("describe", "--tags", "--match", "v[0-9]*", "--abbrev=0", head); err == nil && strings.TrimSpace(out) != "" {
		return strings.TrimSpace(out)
	}
	if out, err := git("rev-parse", head+"^"); err == nil && strings.TrimSpace(out) != "" {
		return strings.TrimSpace(out)
	}
	return EmptyTree
}

func RenderFormula(formulaName string, versionURL string, sha256 string) string {
	className := ""
	for _, part := range strings.Split(strings.ReplaceAll(formulaName, "_", "-"), "-") {
		if part == "" {
			continue
		}
		className += strings.ToUpper(part[:1]) + part[1:]
	}
	return fmt.Sprintf(`# Generated by edwmurph/codux .github/workflows/publish-homebrew.yml.
class %s < Formula
  desc "Coordinate multiple Codex sessions from a single tmux workspace"
  homepage "https://github.com/edwmurph/codux"
  url "%s"
  sha256 "%s"
  license "MIT"

  depends_on "go" => :build
  depends_on "tmux"

  def install
    system "go", "build", "-ldflags", "-X github.com/edwmurph/codux/internal/version.Version=#{version}", "-o", bin/"%s", "./cmd/codux"
  end

  test do
    assert_match "Start, inspect, or detach Codux tmux workspaces", shell_output("#{bin}/%s --help")
    assert_match "tmux", shell_output("#{bin}/%s doctor")
  end
end
`, className, versionURL, sha256, formulaName, formulaName, formulaName)
}

func git(args ...string) (string, error) {
	out, err := exec.Command("git", args...).CombinedOutput()
	return strings.TrimSpace(string(out)), err
}
