from __future__ import annotations

import argparse
from pathlib import Path


FORMULA_HEADER = "# Generated by edwmurph/codux .github/workflows/publish-homebrew.yml.\n"


def class_name(formula_name: str) -> str:
    return "".join(part.capitalize() for part in formula_name.replace("_", "-").split("-"))


def render_formula(
    *,
    formula_name: str,
    version_url: str,
    sha256: str,
    wheel_url: str,
    wheel_sha256: str,
    wheelhouse_url: str,
    wheelhouse_sha256: str,
    python_formula: str,
) -> str:
    python_executable = python_formula.replace("@", "")
    return (
        FORMULA_HEADER
        + f"class {class_name(formula_name)} < Formula\n"
        + "  include Language::Python::Virtualenv\n\n"
        + '  desc "Coordinate multiple Codex sessions from a single tmux workspace"\n'
        + '  homepage "https://github.com/edwmurph/codux"\n'
        + f'  url "{version_url}"\n'
        + f'  sha256 "{sha256}"\n'
        + '  license "MIT"\n\n'
        + f'  depends_on "{python_formula}"\n'
        + '  depends_on "tmux"\n\n'
        + f'  resource "{formula_name}-wheel" do\n'
        + f'    url "{wheel_url}"\n'
        + f'    sha256 "{wheel_sha256}"\n'
        + "  end\n\n"
        + f'  resource "{formula_name}-wheelhouse" do\n'
        + f'    url "{wheelhouse_url}"\n'
        + f'    sha256 "{wheelhouse_sha256}"\n'
        + "  end\n\n"
        + "  def install\n"
        + f'    venv = virtualenv_create(libexec, "{python_executable}")\n'
        + f'    resource("{formula_name}-wheelhouse").stage do\n'
        + '      venv.pip_install Dir["*.whl"].sort\n'
        + "    end\n"
        + f'    resource("{formula_name}-wheel").stage do\n'
        + f'      venv.pip_install_and_link Pathname.pwd/"{formula_name}-#{{version}}-py3-none-any.whl"\n'
        + "    end\n"
        + "  end\n\n"
        + "  test do\n"
        + '    assert_match "Start, inspect, or detach Codux tmux workspaces", shell_output("#{bin}/codux --help")\n'
        + "  end\n"
        + "end\n"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render the Codux Homebrew formula.")
    parser.add_argument("--formula-name", default="codux")
    parser.add_argument("--url", required=True)
    parser.add_argument("--sha256", required=True)
    parser.add_argument("--wheel-url", required=True)
    parser.add_argument("--wheel-sha256", required=True)
    parser.add_argument("--wheelhouse-url", required=True)
    parser.add_argument("--wheelhouse-sha256", required=True)
    parser.add_argument("--python-formula", default="python@3.13")
    parser.add_argument("--output", required=True)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    formula = render_formula(
        formula_name=args.formula_name,
        version_url=args.url,
        sha256=args.sha256,
        wheel_url=args.wheel_url,
        wheel_sha256=args.wheel_sha256,
        wheelhouse_url=args.wheelhouse_url,
        wheelhouse_sha256=args.wheelhouse_sha256,
        python_formula=args.python_formula,
    )
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(formula)


if __name__ == "__main__":
    main()
