from __future__ import annotations

import argparse
import tomllib
from collections.abc import Iterable
from pathlib import Path


FORMULA_HEADER = "# Generated by edwmurph/codux .github/workflows/publish-homebrew.yml.\n"
WINDOWS_MARKERS = (
    "sys_platform == 'win32'",
    'sys_platform == "win32"',
    "platform_system == 'Windows'",
)


def normalized(name: str) -> str:
    return name.replace("_", "-").lower()


def class_name(formula_name: str) -> str:
    return "".join(part.capitalize() for part in formula_name.replace("_", "-").split("-"))


def package_map(lock_data: dict) -> dict[str, dict]:
    return {normalized(package["name"]): package for package in lock_data["package"]}


def should_skip_dependency(dependency: dict) -> bool:
    marker = dependency.get("marker", "")
    return any(windows_marker in marker for windows_marker in WINDOWS_MARKERS)


def runtime_dependencies(lock_data: dict, root: str) -> list[dict]:
    packages = package_map(lock_data)
    root_key = normalized(root)
    ordered: list[dict] = []
    seen: set[str] = set()

    def visit(name: str) -> None:
        key = normalized(name)
        if key in seen:
            return
        package = packages[key]
        for dependency in package.get("dependencies", []):
            if not should_skip_dependency(dependency):
                visit(dependency["name"])
        if key != root_key:
            ordered.append(package)
        seen.add(key)

    visit(root_key)
    return ordered


def resource_block(package: dict) -> str:
    artifact = package_artifact(package)
    sha256 = artifact["hash"].removeprefix("sha256:")
    return "\n".join(
        [
            f'  resource "{package["name"]}" do',
            f'    url "{artifact["url"]}"',
            f'    sha256 "{sha256}"',
            "  end",
        ]
    )


def package_artifact(package: dict) -> dict:
    for wheel in package.get("wheels", []):
        if wheel["url"].endswith("-none-any.whl"):
            return wheel
    sdist = package.get("sdist")
    if not sdist:
        raise ValueError(f"package {package['name']} has no wheel or sdist in uv.lock")
    return sdist


def resource_blocks(packages: Iterable[dict]) -> str:
    return "\n\n".join(resource_block(package) for package in packages)


def render_formula(
    *,
    formula_name: str,
    version_url: str,
    sha256: str,
    wheel_url: str,
    wheel_sha256: str,
    python_formula: str,
    lock_data: dict,
) -> str:
    resources = resource_blocks(runtime_dependencies(lock_data, formula_name))
    python_executable = python_formula.replace("@", "")
    return (
        FORMULA_HEADER
        + f"class {class_name(formula_name)} < Formula\n"
        + "  include Language::Python::Virtualenv\n\n"
        + '  desc "Coordinate multiple Codex sessions from a single tmux workspace"\n'
        + '  homepage "https://github.com/edwmurph/codux"\n'
        + f'  url "{version_url}"\n'
        + f'  sha256 "{sha256}"\n'
        + '  license "MIT"\n\n'
        + f'  depends_on "{python_formula}"\n'
        + '  depends_on "tmux"\n\n'
        + f'  resource "{formula_name}-wheel" do\n'
        + f'    url "{wheel_url}"\n'
        + f'    sha256 "{wheel_sha256}"\n'
        + "  end\n\n"
        + resources
        + "\n\n"
        + "  def install\n"
        + f'    venv = virtualenv_create(libexec, "{python_executable}")\n'
        + f'    venv.pip_install resources.reject {{ |resource| resource.name == "{formula_name}-wheel" }}\n'
        + f'    resource("{formula_name}-wheel").stage do\n'
        + f'      venv.pip_install_and_link Pathname.pwd/"{formula_name}-#{{version}}-py3-none-any.whl"\n'
        + "    end\n"
        + '    rm bin/"start" if (bin/"start").exist?\n'
        + "  end\n\n"
        + "  test do\n"
        + '    assert_match "Start, inspect, or detach Codux tmux workspaces", shell_output("#{bin}/codux --help")\n'
        + "  end\n"
        + "end\n"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render the Codux Homebrew formula.")
    parser.add_argument("--formula-name", default="codux")
    parser.add_argument("--url", required=True)
    parser.add_argument("--sha256", required=True)
    parser.add_argument("--wheel-url", required=True)
    parser.add_argument("--wheel-sha256", required=True)
    parser.add_argument("--python-formula", default="python@3.13")
    parser.add_argument("--lock-file", default="uv.lock")
    parser.add_argument("--output", required=True)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    lock_data = tomllib.loads(Path(args.lock_file).read_text())
    formula = render_formula(
        formula_name=args.formula_name,
        version_url=args.url,
        sha256=args.sha256,
        wheel_url=args.wheel_url,
        wheel_sha256=args.wheel_sha256,
        python_formula=args.python_formula,
        lock_data=lock_data,
    )
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(formula)


if __name__ == "__main__":
    main()
